import 'package:get/get.dart';

class Languages extends Translations{
  @override
  Map<String, Map<String, String>> get keys=>{
    "en_US":{
      "splashScreen":"Gallery",
      "localImages":"Local Images",
      "no_image":"No Image",
      "search":"Search",
      "try_again":"Try again",
      "search_something":"Search Something",
      "clear_images":"Clear all local images",
      "description":"Description: ",
      "photographer_id":"Photographer id: ",
      "photographer":"Photographer name: ",
      "image_detail":"Image Detail",
      "no_internet":"No Internet",
      "something_wrong":"Something went wrong",
      "bad_request":"Bad Request",
      "time_out":"Time out",
      "add_image":"Add Image",
      "image_added":"Image added",
      "select_image":"Select Image",
      "p_select_image":"Please Select Image",
      "camera":"Camera",
      "gallery":"Gallery",
      "home":"Home",
      "settings":"Settings",
      "enter_text":"please enter text",
      "select_theme":"Select Theme",
      "images_cleared":"Images Cleared",
      "system":"System",
      "light":"Light",
      "dark":"Dark",
      "switch_language":"Switch Language",
    },
    "ur_PK":{
      "splashScreen":"گیلری",
      "localImages":"مقامی تصاویر",
      "no_image":"کوئی تصویر نہیں۔",
      "search":"تلاش کریں۔",
      "try_again":"دوبارہ کوشش کریں۔",
      "search_something":"کچھ تلاش کریں۔",
      "clear_images":"تمام مقامی تصاویر کو صاف کریں۔",
      "description":"تفصیل: ",
      "photographer_id":"فوٹوگرافر کی شناخت: ",
      "photographer":"فوٹوگرافر کا نام: ",
      "image_detail":"تصویر کی تفصیل",
      "no_internet":"انٹرنیٹ نہیں ہے۔",
      "something_wrong":"کچھ غلط ہو گیا۔",
      "bad_request":"بری درخواست",
      "time_out":"وقت ختم",
      "add_image":"تصویر شامل کریں۔",
      "image_added":"تصویر شامل کی گئی۔",
      "select_image":"تصویر منتخب کریں۔",
      "p_select_image":"براہ کرم تصویر منتخب کریں۔",
      "camera":"کیمرہ",
      "gallery":"گیلری",
      "home":"گھر",
      "settings":"ترتیبات",
      "enter_text":"براہ کرم متن درج کریں۔",
      "select_theme":"تھیم منتخب کریں۔",
      "images_cleared":"تصاویر صاف کر دی گئیں۔",
      "system":"سسٹم",
      "light":"روشنی",
      "dark":"اندھیرا",
      "switch_language":"زبان سوئچ کریں۔",

    }
  };


}